# ---------------------------------------------------------------------------------------
# 🐳 Docker Compose file for OpenFactory Fan-out Layer
# ---------------------------------------------------------------------------------------
#
# This file defines the services required to run the OpenFactory Fan-out Layer stack:
# 1. asset-forwarder   - Streams asset data to Kafka and NATS (scalable service)
# 2. asset-router      - Provides deterministic routing of asset IDs to NATS clusters
# 3. nats              - Provides lightweight messaging backbone for coordination
#
# All services are connected through the 'factory-net' Docker network.
#
# ---------------------------------------------------------------------------------------
# Intended usage:
#   - This compose file is designed for developers to easily start and test the
#     OpenFactory Fan-out Layer locally.
#   - It can also serve as a starting point for production deployment with
#     additional configuration.
#
# ---------------------------------------------------------------------------------------
# Usage:
#   # Start services
#   docker compose up -d
#
#   # Stop services
#   docker compose down
#
#   # Scale number of forwarders (example: 3 replicas)
#   docker compose up -d --scale asset-forwarder=3
#
# ---------------------------------------------------------------------------------------
# Environment variables for asset-forwarder:
#
# Required:
#   KAFKA_BROKER                Kafka bootstrap server
#
# Optional:
#   FORWARDER_VERSION           Version tag for the asset-forwarder image (default: latest)
#   ASSET_FORWARDER_LOG_LEVEL   Log level (default: INFO)
#
# Fixed (do not change unless customizing deployment):
#   NATS_CLUSTER_C1             NATS cluster URL (default: nats://nats:4222)
#
# ---------------------------------------------------------------------------------------
# Environment variables for asset-router:
#
# Optional:
#   ASSET_ROUTER_VERSION        Version tag for the asset-router image (default: latest)
#   ASSET_ROUTER_URL            NATS cluster URL to route assets to (default: nats://nats:4222)
#
# ---------------------------------------------------------------------------------------
# Ports:
#   asset-router: 8002
#   NATS: 4222
#
# ---------------------------------------------------------------------------------------
# External network required:
#   factory-net
# ---------------------------------------------------------------------------------------

services:
  asset-forwarder:
    image: ghcr.io/openfactoryio/asset-forwarder:${ASSET_FORWARDER_VERSION}
    environment:
      - KAFKA_BROKER=${KAFKA_BROKER}
      - NATS_CLUSTER_C1=nats://nats:4222
      - ASSET_FORWARDER_LOG_LEVEL=${ASSET_FORWARDER_LOG_LEVEL:-INFO}
    networks:
      - factory-net

  asset-router:
    image: ghcr.io/openfactoryio/asset-router:${ASSET_ROUTER_VERSION}
    environment:
      - NATS_CLUSTER_C1=${ASSET_ROUTER_URL:-nats://nats:4222}
    ports:
      - "8002:8002"
    networks:
      - factory-net

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    networks:
      - factory-net

networks:

    factory-net:
      external: true
